pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout from the master branch
                git url: 'https://github.com/saikartik196/my-node-app.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def imageName = 'my-node-app'
                    if (isUnix()) {
                        sh "docker build -t ${imageName} ."
                    } else {
                        bat "docker build -t ${imageName} ."
                    }
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    if (isUnix()) {
                        sh "docker run -d -p 3000:3000 ${imageName}"
                    } else {
                        bat "docker run -d -p 3000:3000 ${imageName}"
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
